# 配置数据库连接

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 556688
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

##
server:
  port: 8002